-- =========================================================================
-- 클래스픽 v7.1 seed — 5개 학원 강좌 데이터
-- Generated from index.html EDUIN_COURSES + MYUNGIN_COURSES + MYUNGJAK_COURSES + DEMO
-- Idempotent: on conflict do update set ... (re-running overwrites).
-- =========================================================================

insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin0','부산','센텀','교육인학원 센텀점','부일고1 수학 수파르타','수학','김형석','고1',ARRAY['월','화','수','목','금']::text[],'오전','10:00-15:00','주 5회','부일고','부일고1','방학특강',ARRAY['7','8']::text[],'7월 말 개강 / 부일고 자사고 수학 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin2','부산','센텀','교육인학원 센텀점','부일고2 수학 수파르타','수학','김형석','고2',ARRAY['월','화','수','목','금']::text[],'오전','10:00-15:00','주 5회','부일고','부일고2','방학특강',ARRAY['7','8']::text[],'7월 말 개강 / 부일고 수학 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin3','부산','센텀','교육인학원 센텀점','해운대고1 수학 수파르타 (평일)','수학','이영환','고1',ARRAY['월','수','금']::text[],'저녁','17:00-22:00','주 3회','해운대고','해운대고1','방학특강',ARRAY['7','8']::text[],'7월 말 개강 / 해운대고 수학 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin4','부산','센텀','교육인학원 센텀점','해운대고1 수학 수파르타 (주말)','수학','이영환','고1',ARRAY['토','일']::text[],'오전','10:00-13:00','주 2회','해운대고','해운대고1','방학특강',ARRAY['7','8']::text[],'7월 말 개강 / 평일반과 함께 주 5회','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin6','부산','센텀','교육인학원 센텀점','해운대고2 수학 수파르타 (평일)','수학','차동우','고2',ARRAY['월','화','수','목','금']::text[],'저녁','20:00-23:00','주 5회','해운대고','해운대고2','방학특강',ARRAY['7','8']::text[],'7월 말 개강','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin7','부산','센텀','교육인학원 센텀점','해운대고2 수학 수파르타 (일요)','수학','차동우','고2',ARRAY['일']::text[],'오전','10:00-13:00','주 1회 추가','해운대고','해운대고2','방학특강',ARRAY['7','8']::text[],'7월 말 개강 / 평일반과 병행','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin8','부산','센텀','교육인학원 센텀점','고3 수능 수학 2등급 반년컷','수학',null,'고3',ARRAY['토','일']::text[],'오후',null,'주 2회',null,null,'방학특강',ARRAY['6','7','8','9','10','11']::text[],'6월 개강 / 6월 모평 4등급 이하 집중','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin9','부산','센텀','교육인학원 센텀점','고3 수능 영어 1등급 반년컷','영어',null,'고3',ARRAY['일']::text[],'오후',null,'주 1회',null,null,'방학특강',ARRAY['6','7','8','9','10','11']::text[],'6월 개강','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin10','부산','센텀','교육인학원 센텀점','부일고1 수학 (자사특목·공수1)','수학','김형석','고1',ARRAY['토']::text[],'오전','10:00-13:00','주 1회 (토)','부일고','부일고1','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목 정규 / 공통수학1','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin11','부산','센텀','교육인학원 센텀점','부일고1 수학 (자사특목·공수2)','수학','김형석','고1',ARRAY['일']::text[],'오전','10:00-13:00','주 1회 (일)','부일고','부일고1','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목 정규 / 공통수학2','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin12','부산','센텀','교육인학원 센텀점','부일고1 영어 (자사특목)','영어','윤훈관','고1',ARRAY['토']::text[],'오후','14:00-18:00','주 1회','부일고','부일고1','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목 정규 / 부일고 영어 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin13','부산','센텀','교육인학원 센텀점','부산외고1 수학 A (오전)','수학','차동우','고1',ARRAY['토','일']::text[],'오전','10:00-13:00','주 2회 (오전반)','부산외고','부산외고1','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목 / 부산외고 수학 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin14','부산','센텀','교육인학원 센텀점','부산외고1 수학 B (오후)','수학','차동우','고1',ARRAY['토','일']::text[],'오후','13:30-16:30','주 2회 (오후반)','부산외고','부산외고1','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목 / 부산외고 수학 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin16','부산','센텀','교육인학원 센텀점','부산외고1 통합사회','사회','김규생','고1',ARRAY['일']::text[],'오전','09:30-12:30','주 1회','부산외고','부산외고1','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목 / 부산외고 통사 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin17','부산','센텀','교육인학원 센텀점','해운대고1 수학 (자사특목·공수1)','수학','이영환','고1',ARRAY['토']::text[],'오전','10:00-13:00','주 1회 (토)','해운대고','해운대고1','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목 / 공통수학1','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin18','부산','센텀','교육인학원 센텀점','해운대고1 수학 (자사특목·공수2)','수학','이영환','고1',ARRAY['일']::text[],'오전','10:00-13:00','주 1회 (일)','해운대고','해운대고1','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목 / 공통수학2','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin19','부산','센텀','교육인학원 센텀점','해운대고1 수학 클리닉 CORE','수학','이영환','고1',ARRAY['일']::text[],'저녁','19:00-22:00','주 1회','해운대고','해운대고1','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목 / 개인별 맞춤 클리닉','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin20','부산','센텀','교육인학원 센텀점','해운대고1 수학 클리닉 MASTER','수학','이영환','고1',ARRAY['화']::text[],'저녁','20:00-23:00','주 1회','해운대고','해운대고1','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목 / 개인별 맞춤 클리닉','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin21','부산','센텀','교육인학원 센텀점','해운대고1 영어 (자사특목)','영어','윤훈관','고1',ARRAY['일']::text[],'오후','14:00-18:00','주 1회','해운대고','해운대고1','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목 / 해운대고 영어 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin24','부산','센텀','교육인학원 센텀점','부일고2 수학 (미적분1 심화)','수학','김형석','고2',ARRAY['토','일']::text[],'오후','13:00-16:00','주 2회','부일고','부일고2','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목 / 미적분1 심화','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin25','부산','센텀','교육인학원 센텀점','부일고2 영어 (자사특목)','영어','윤훈관','고2',ARRAY['일']::text[],'오전','09:00-13:00','주 1회','부일고','부일고2','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin26','부산','센텀','교육인학원 센텀점','부산외고2 수학 S (100점 목표)','수학','김형석','고2',ARRAY['토']::text[],'저녁','19:00-23:00','주 1회','부산외고','부산외고2','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목 / 100점 목표','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin27','부산','센텀','교육인학원 센텀점','부산외고2 영어','영어','윤훈관','고2',ARRAY['토']::text[],'오전','09:00-13:00','주 1회','부산외고','부산외고2','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin28','부산','센텀','교육인학원 센텀점','부산외고2 국어','국어','전인재','고2',ARRAY['일']::text[],'오전','10:00-13:00','주 1회','부산외고','부산외고2','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin29','부산','센텀','교육인학원 센텀점','부산외고2 국제계열 사회','사회','김규생','고2',ARRAY['일']::text[],'저녁','20:00-23:00','주 1회','부산외고','부산외고2','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목 / 국제계열','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin30','부산','센텀','교육인학원 센텀점','해운대고2 영어 (자사특목)','영어','윤훈관','고2',ARRAY['일']::text[],'저녁','19:00-23:00','주 1회','해운대고','해운대고2','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin31','부산','센텀','교육인학원 센텀점','부산예고1 수학','수학','차동우','고1',ARRAY['토']::text[],'저녁','20:00-23:00','주 1회','부산예고','부산예고1','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin32','부산','센텀','교육인학원 센텀점','부산예고1 영어','영어','권정은','고1',ARRAY['월']::text[],'저녁','19:00-23:00','주 1회','부산예고','부산예고1','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin33','부산','센텀','교육인학원 센텀점','해강고1 수학 (수요반)','수학','차동우','고1',ARRAY['수']::text[],'저녁','20:00-23:00','주 1회 (수)','해강고','해강고1','학교내신',ARRAY['5','6','7','8','9','10','11','12']::text[],'해강고 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin34','부산','센텀','교육인학원 센텀점','해강고1 수학 (토요반)','수학','차동우','고1',ARRAY['토']::text[],'오후','16:00-19:00','주 1회 (토)','해강고','해강고1','학교내신',ARRAY['5','6','7','8','9','10','11','12']::text[],'해강고 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin35','부산','센텀','교육인학원 센텀점','해강고1 영어','영어','권정은','고1',ARRAY['화']::text[],'저녁','19:00-23:00','주 1회','해강고','해강고1','학교내신',ARRAY['5','6','7','8','9','10','11','12']::text[],'해강고 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin36','부산','센텀','교육인학원 센텀점','센텀여고1 수학 (화요반)','수학','김명욱','고1',ARRAY['화']::text[],'저녁','20:00-23:00','주 1회 (화)','센텀여고','센텀여고1','학교내신',ARRAY['5','6','7','8','9','10','11','12']::text[],'센텀여고 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin37','부산','센텀','교육인학원 센텀점','센텀여고1 수학 (토요반)','수학','김명욱','고1',ARRAY['토']::text[],'오후','14:00-17:00','주 1회 (토)','센텀여고','센텀여고1','학교내신',ARRAY['5','6','7','8','9','10','11','12']::text[],'센텀여고 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin38','부산','센텀','교육인학원 센텀점','센텀여고1 영어','영어','윤훈관','고1',ARRAY['수']::text[],'저녁','19:00-23:00','주 1회','센텀여고','센텀여고1','학교내신',ARRAY['5','6','7','8','9','10','11','12']::text[],'센텀여고 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin39','부산','센텀','교육인학원 센텀점','센텀여고1 국어','국어','교육인 국어팀','고1',ARRAY['토']::text[],'오후','17:00-20:00','주 1회','센텀여고','센텀여고1','학교내신',ARRAY['5','6','7','8','9','10','11','12']::text[],'센텀여고 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin40','부산','센텀','교육인학원 센텀점','덕문여고1 영어','영어','권정은','고1',ARRAY['토']::text[],'오후','13:00-17:00','주 1회','덕문여고','덕문여고1','학교내신',ARRAY['5','6','7','8','9','10','11','12']::text[],'덕문여고 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin41','부산','센텀','교육인학원 센텀점','센텀고1 수학 (목요반)','수학','김명욱','고1',ARRAY['목']::text[],'저녁','20:00-23:00','주 1회 (목)','센텀고','센텀고1','학교내신',ARRAY['5','6','7','8','9','10','11','12']::text[],'센텀고 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin42','부산','센텀','교육인학원 센텀점','센텀고1 수학 (일요반)','수학','김명욱','고1',ARRAY['일']::text[],'저녁','18:00-21:00','주 1회 (일)','센텀고','센텀고1','학교내신',ARRAY['5','6','7','8','9','10','11','12']::text[],'센텀고 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin43','부산','센텀','교육인학원 센텀점','학산여고1 영어','영어','권정은','고1',ARRAY['월']::text[],'저녁','19:00-23:00','주 1회','학산여고','학산여고1','학교내신',ARRAY['5','6','7','8','9','10','11','12']::text[],'학산여고 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin44','부산','센텀','교육인학원 센텀점','덕문여고2 수학','수학','김형석','고2',ARRAY['수','금']::text[],'저녁','20:00-23:00','주 2회','덕문여고','덕문여고2','학교내신',ARRAY['5','6','7','8','9','10','11','12']::text[],'덕문여고 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin45','부산','센텀','교육인학원 센텀점','덕문여고2 영어','영어','권정은','고2',ARRAY['토']::text[],'저녁','19:00-23:00','주 1회','덕문여고','덕문여고2','학교내신',ARRAY['5','6','7','8','9','10','11','12']::text[],'덕문여고 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin46','부산','센텀','교육인학원 센텀점','동여고2 수학','수학','김형석','고2',ARRAY['수','금']::text[],'저녁','20:00-23:00','주 2회','동여고','동여고2','학교내신',ARRAY['5','6','7','8','9','10','11','12']::text[],'동여고 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin47','부산','센텀','교육인학원 센텀점','고3 수능실전대비반','영어','정준호','고3',ARRAY['일']::text[],'오후','13:00-16:00','주 1회',null,null,'수능대비',ARRAY['3','4','5','6','7','8','9','10','11']::text[],'고3·재수생 / 100점 목표','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin48','부산','센텀','교육인학원 센텀점','고3 보카트레이닝','영어',null,'고3',ARRAY['일']::text[],'오후','17:00-20:00','주 1회',null,null,'수능대비',ARRAY['3','4','5','6','7','8','9','10','11']::text[],'고3·재수생 / 단어 200개/회','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin49','부산','센텀','교육인학원 센텀점','중등 SUMMIT S','영어',null,'중3',ARRAY['화','목']::text[],'오후','17:00-20:00','주 2회',null,null,'상위권',ARRAY['5','6','7','8','9','10','11','12']::text[],'최상위 영어 실력','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin50','부산','센텀','교육인학원 센텀점','중등 SUMMIT K','영어',null,'중3',ARRAY['월','금']::text[],'저녁','20:00-23:00','주 2회',null,null,'상위권',ARRAY['5','6','7','8','9','10','11','12']::text[],'최상위 영어 실력','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin51','부산','센텀','교육인학원 센텀점','중등 문법 LEVEL3','영어',null,'중3',ARRAY['수']::text[],'저녁','20:00-23:00','주 1회',null,null,'문법',ARRAY['5','6','7','8','9','10','11','12']::text[],'학교별·수준별 내신 문법','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin52','부산','센텀','교육인학원 센텀점','중등 문법 LEVEL2 (화반)','영어',null,'중3',ARRAY['화']::text[],'오후','17:00-20:00','주 1회',null,null,'문법',ARRAY['5','6','7','8','9','10','11','12']::text[],'내신 문법 LEVEL2','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin53','부산','센텀','교육인학원 센텀점','중등 문법 LEVEL2 (수반)','영어',null,'중3',ARRAY['수']::text[],'오후','17:00-20:00','주 1회',null,null,'문법',ARRAY['5','6','7','8','9','10','11','12']::text[],'내신 문법 LEVEL2','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin54','부산','센텀','교육인학원 센텀점','중등 문법 LEVEL1','영어',null,'중3',ARRAY['수']::text[],'오후','17:00-20:00','주 1회',null,null,'문법',ARRAY['5','6','7','8','9','10','11','12']::text[],'내신 문법 LEVEL1','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin55','부산','센텀','교육인학원 센텀점','중등 독해 LEVEL3','영어',null,'중3',ARRAY['금']::text[],'저녁','20:00-23:00','주 1회',null,null,'독해',ARRAY['5','6','7','8','9','10','11','12']::text[],'내신 독해 LEVEL3','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin56','부산','센텀','교육인학원 센텀점','중등 독해 LEVEL2 (목반)','영어',null,'중3',ARRAY['목']::text[],'오후','17:00-20:00','주 1회',null,null,'독해',ARRAY['5','6','7','8','9','10','11','12']::text[],'내신 독해 LEVEL2','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin57','부산','센텀','교육인학원 센텀점','중등 독해 LEVEL2 (금반)','영어',null,'중3',ARRAY['금']::text[],'오후','17:00-20:00','주 1회',null,null,'독해',ARRAY['5','6','7','8','9','10','11','12']::text[],'내신 독해 LEVEL2','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin58','부산','센텀','교육인학원 센텀점','중등 독해 LEVEL1','영어',null,'중3',ARRAY['금']::text[],'오후','17:00-20:00','주 1회',null,null,'독해',ARRAY['5','6','7','8','9','10','11','12']::text[],'내신 독해 LEVEL1','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin59','부산','센텀','교육인학원 센텀점','수능형 사고력 12개월완성 (화반)','영어',null,'중3',ARRAY['화']::text[],'저녁','19:00-23:00','주 1회',null,null,'수능대비',ARRAY['5','6','7','8','9','10','11','12']::text[],'중학생 대상 1년 완성 수능형 영어','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin60','부산','센텀','교육인학원 센텀점','수능형 사고력 12개월완성 (목반)','영어',null,'중3',ARRAY['목']::text[],'저녁','19:00-23:00','주 1회',null,null,'수능대비',ARRAY['5','6','7','8','9','10','11','12']::text[],'중학생 대상 1년 완성 수능형 영어','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin61','부산','센텀','교육인학원 센텀점','중등 보카트레이닝','영어',null,'중3',ARRAY['월']::text[],'오후','17:00-20:00','주 1회',null,null,'단어',ARRAY['5','6','7','8','9','10','11','12']::text[],'중등 / 단어 200개/회','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin62','부산','센텀','교육인학원 센텀점','공통수학1 (심화) 공.심.쟁','수학','김형석','고1',ARRAY['수']::text[],'오후','17:00-18:30','주 1회',null,null,'심화',ARRAY['5','6','7','8','9','10','11','12']::text[],'교재: 고쟁이','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin63','부산','센텀','교육인학원 센텀점','공통수학2 (심화) 공.심.쟁','수학','김형석','고1',ARRAY['화','목']::text[],'오후','17:00-20:00','주 1회',null,null,'심화',ARRAY['5','6','7','8','9','10','11','12']::text[],'교재: 고쟁이','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin64','부산','센텀','교육인학원 센텀점','대수 (심화) 대.심.쟁','수학','김형석','고1',ARRAY['수']::text[],'오후','18:30-20:00','주 1회',null,null,'심화',ARRAY['5','6','7','8','9','10','11','12']::text[],'교재: 고쟁이','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin65','부산','센텀','교육인학원 센텀점','미적분1 개별진도 (김명욱T)','수학','김명욱','고2',ARRAY['화','목']::text[],'오후','17:00-20:00','주 2회',null,null,'개별진도',ARRAY['5','6','7','8','9','10','11','12']::text[],'개인별 맞춤 수업','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin66','부산','센텀','교육인학원 센텀점','미적분1 개별진도 (이영환T)','수학','이영환','고2',ARRAY['화','목']::text[],'오후','17:00-20:00','주 2회',null,null,'개별진도',ARRAY['5','6','7','8','9','10','11','12']::text[],'개인별 맞춤 교재+진도','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin67','부산','센텀','교육인학원 센텀점','미적분1 수능대비 (강필T)','수학','강필','고2',ARRAY['일']::text[],'저녁','17:30-21:30','주 1회',null,null,'수능대비',ARRAY['5','6','7','8','9','10','11','12']::text[],'1등급 목표','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
