-- =========================================================================
-- 클래스픽 v7.1 seed — 5개 학원 강좌 데이터
-- Generated from index.html EDUIN_COURSES + MYUNGIN_COURSES + MYUNGJAK_COURSES + DEMO
-- Idempotent: on conflict do update set ... (re-running overwrites).
-- =========================================================================

insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin0','부산','센텀','교육인학원 센텀점','부일고1 수학 수파르타','수학','김형석','고1',ARRAY['월','화','수','목','금']::text[],'오전','10:00-15:00','주 5회','부일고','부일고1','방학특강',ARRAY['7','8']::text[],'7월 말 개강 / 부일고 자사고 수학 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin2','부산','센텀','교육인학원 센텀점','부일고2 수학 수파르타','수학','김형석','고2',ARRAY['월','화','수','목','금']::text[],'오전','10:00-15:00','주 5회','부일고','부일고2','방학특강',ARRAY['7','8']::text[],'7월 말 개강 / 부일고 수학 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin3','부산','센텀','교육인학원 센텀점','해운대고1 수학 수파르타 (평일)','수학','이영환','고1',ARRAY['월','수','금']::text[],'저녁','17:00-22:00','주 3회','해운대고','해운대고1','방학특강',ARRAY['7','8']::text[],'7월 말 개강 / 해운대고 수학 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin4','부산','센텀','교육인학원 센텀점','해운대고1 수학 수파르타 (주말)','수학','이영환','고1',ARRAY['토','일']::text[],'오전','10:00-13:00','주 2회','해운대고','해운대고1','방학특강',ARRAY['7','8']::text[],'7월 말 개강 / 평일반과 함께 주 5회','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin6','부산','센텀','교육인학원 센텀점','해운대고2 수학 수파르타 (평일)','수학','차동우','고2',ARRAY['월','화','수','목','금']::text[],'저녁','20:00-23:00','주 5회','해운대고','해운대고2','방학특강',ARRAY['7','8']::text[],'7월 말 개강','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin7','부산','센텀','교육인학원 센텀점','해운대고2 수학 수파르타 (일요)','수학','차동우','고2',ARRAY['일']::text[],'오전','10:00-13:00','주 1회 추가','해운대고','해운대고2','방학특강',ARRAY['7','8']::text[],'7월 말 개강 / 평일반과 병행','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin10','부산','센텀','교육인학원 센텀점','부일고1 수학 (자사특목·공수1)','수학','김형석','고1',ARRAY['토']::text[],'오전','10:00-13:00','주 1회 (토)','부일고','부일고1','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목 정규 / 공통수학1','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin11','부산','센텀','교육인학원 센텀점','부일고1 수학 (자사특목·공수2)','수학','김형석','고1',ARRAY['일']::text[],'오전','10:00-13:00','주 1회 (일)','부일고','부일고1','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목 정규 / 공통수학2','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin12','부산','센텀','교육인학원 센텀점','부일고1 영어 (자사특목)','영어','윤훈관','고1',ARRAY['토']::text[],'오후','14:00-18:00','주 1회','부일고','부일고1','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목 정규 / 부일고 영어 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin13','부산','센텀','교육인학원 센텀점','부산외고1 수학 A (오전)','수학','차동우','고1',ARRAY['토','일']::text[],'오전','10:00-13:00','주 2회 (오전반)','부산외고','부산외고1','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목 / 부산외고 수학 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin14','부산','센텀','교육인학원 센텀점','부산외고1 수학 B (오후)','수학','차동우','고1',ARRAY['토','일']::text[],'오후','13:30-16:30','주 2회 (오후반)','부산외고','부산외고1','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목 / 부산외고 수학 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin16','부산','센텀','교육인학원 센텀점','부산외고1 통합사회','사회','김규생','고1',ARRAY['일']::text[],'오전','09:30-12:30','주 1회','부산외고','부산외고1','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목 / 부산외고 통사 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin17','부산','센텀','교육인학원 센텀점','해운대고1 수학 (자사특목·공수1)','수학','이영환','고1',ARRAY['토']::text[],'오전','10:00-13:00','주 1회 (토)','해운대고','해운대고1','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목 / 공통수학1','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin18','부산','센텀','교육인학원 센텀점','해운대고1 수학 (자사특목·공수2)','수학','이영환','고1',ARRAY['일']::text[],'오전','10:00-13:00','주 1회 (일)','해운대고','해운대고1','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목 / 공통수학2','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin19','부산','센텀','교육인학원 센텀점','해운대고1 수학 클리닉 CORE','수학','이영환','고1',ARRAY['일']::text[],'저녁','19:00-22:00','주 1회','해운대고','해운대고1','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목 / 개인별 맞춤 클리닉','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin20','부산','센텀','교육인학원 센텀점','해운대고1 수학 클리닉 MASTER','수학','이영환','고1',ARRAY['화']::text[],'저녁','20:00-23:00','주 1회','해운대고','해운대고1','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목 / 개인별 맞춤 클리닉','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin21','부산','센텀','교육인학원 센텀점','해운대고1 영어 (자사특목)','영어','윤훈관','고1',ARRAY['일']::text[],'오후','14:00-18:00','주 1회','해운대고','해운대고1','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목 / 해운대고 영어 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin24','부산','센텀','교육인학원 센텀점','부일고2 수학 (미적분1 심화)','수학','김형석','고2',ARRAY['토','일']::text[],'오후','13:00-16:00','주 2회','부일고','부일고2','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목 / 미적분1 심화','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin25','부산','센텀','교육인학원 센텀점','부일고2 영어 (자사특목)','영어','윤훈관','고2',ARRAY['일']::text[],'오전','09:00-13:00','주 1회','부일고','부일고2','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin26','부산','센텀','교육인학원 센텀점','부산외고2 수학 S (100점 목표)','수학','김형석','고2',ARRAY['토']::text[],'저녁','19:00-23:00','주 1회','부산외고','부산외고2','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목 / 100점 목표','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin27','부산','센텀','교육인학원 센텀점','부산외고2 영어','영어','윤훈관','고2',ARRAY['토']::text[],'오전','09:00-13:00','주 1회','부산외고','부산외고2','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin29','부산','센텀','교육인학원 센텀점','부산외고2 국제계열 사회','사회','김규생','고2',ARRAY['일']::text[],'저녁','20:00-23:00','주 1회','부산외고','부산외고2','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목 / 국제계열','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin30','부산','센텀','교육인학원 센텀점','해운대고2 영어 (자사특목)','영어','윤훈관','고2',ARRAY['일']::text[],'저녁','19:00-23:00','주 1회','해운대고','해운대고2','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin31','부산','센텀','교육인학원 센텀점','부산예고1 수학','수학','차동우','고1',ARRAY['토']::text[],'저녁','20:00-23:00','주 1회','부산예고','부산예고1','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin32','부산','센텀','교육인학원 센텀점','부산예고1 영어','영어','권정은','고1',ARRAY['월']::text[],'저녁','19:00-23:00','주 1회','부산예고','부산예고1','자사특목',ARRAY['5','6','7','8','9','10','11','12']::text[],'자사특목','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin33','부산','센텀','교육인학원 센텀점','해강고1 수학 (수요반)','수학','차동우','고1',ARRAY['수']::text[],'저녁','20:00-23:00','주 1회 (수)','해강고','해강고1','학교내신',ARRAY['5','6','7','8','9','10','11','12']::text[],'해강고 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin34','부산','센텀','교육인학원 센텀점','해강고1 수학 (토요반)','수학','차동우','고1',ARRAY['토']::text[],'오후','16:00-19:00','주 1회 (토)','해강고','해강고1','학교내신',ARRAY['5','6','7','8','9','10','11','12']::text[],'해강고 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin35','부산','센텀','교육인학원 센텀점','해강고1 영어','영어','권정은','고1',ARRAY['화']::text[],'저녁','19:00-23:00','주 1회','해강고','해강고1','학교내신',ARRAY['5','6','7','8','9','10','11','12']::text[],'해강고 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin38','부산','센텀','교육인학원 센텀점','센텀여고1 영어','영어','윤훈관','고1',ARRAY['수']::text[],'저녁','19:00-23:00','주 1회','센텀여고','센텀여고1','학교내신',ARRAY['5','6','7','8','9','10','11','12']::text[],'센텀여고 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin40','부산','센텀','교육인학원 센텀점','덕문여고1 영어','영어','권정은','고1',ARRAY['토']::text[],'오후','13:00-17:00','주 1회','덕문여고','덕문여고1','학교내신',ARRAY['5','6','7','8','9','10','11','12']::text[],'덕문여고 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin43','부산','센텀','교육인학원 센텀점','학산여고1 영어','영어','권정은','고1',ARRAY['월']::text[],'저녁','19:00-23:00','주 1회','학산여고','학산여고1','학교내신',ARRAY['5','6','7','8','9','10','11','12']::text[],'학산여고 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin44','부산','센텀','교육인학원 센텀점','덕문여고2 수학','수학','김형석','고2',ARRAY['수','금']::text[],'저녁','20:00-23:00','주 2회','덕문여고','덕문여고2','학교내신',ARRAY['5','6','7','8','9','10','11','12']::text[],'덕문여고 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin45','부산','센텀','교육인학원 센텀점','덕문여고2 영어','영어','권정은','고2',ARRAY['토']::text[],'저녁','19:00-23:00','주 1회','덕문여고','덕문여고2','학교내신',ARRAY['5','6','7','8','9','10','11','12']::text[],'덕문여고 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin46','부산','센텀','교육인학원 센텀점','동여고2 수학','수학','김형석','고2',ARRAY['수','금']::text[],'저녁','20:00-23:00','주 2회','동여고','동여고2','학교내신',ARRAY['5','6','7','8','9','10','11','12']::text[],'동여고 내신대비','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin59','부산','센텀','교육인학원 센텀점','수능형 사고력 12개월완성 (화반)','영어',null,'중3',ARRAY['화']::text[],'저녁','19:00-23:00','주 1회',null,null,'수능대비',ARRAY['5','6','7','8','9','10','11','12']::text[],'중학생 대상 1년 완성 수능형 영어','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin60','부산','센텀','교육인학원 센텀점','수능형 사고력 12개월완성 (목반)','영어',null,'중3',ARRAY['목']::text[],'저녁','19:00-23:00','주 1회',null,null,'수능대비',ARRAY['5','6','7','8','9','10','11','12']::text[],'중학생 대상 1년 완성 수능형 영어','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin62','부산','센텀','교육인학원 센텀점','공통수학1 (심화) 공.심.쟁','수학','김형석','고1',ARRAY['수']::text[],'오후','17:00-18:30','주 1회',null,null,'심화',ARRAY['5','6','7','8','9','10','11','12']::text[],'교재: 고쟁이','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin63','부산','센텀','교육인학원 센텀점','공통수학2 (심화) 공.심.쟁','수학','김형석','고1',ARRAY['화','목']::text[],'오후','17:00-20:00','주 1회',null,null,'심화',ARRAY['5','6','7','8','9','10','11','12']::text[],'교재: 고쟁이','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin64','부산','센텀','교육인학원 센텀점','대수 (심화) 대.심.쟁','수학','김형석','고1',ARRAY['수']::text[],'오후','18:30-20:00','주 1회',null,null,'심화',ARRAY['5','6','7','8','9','10','11','12']::text[],'교재: 고쟁이','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin66','부산','센텀','교육인학원 센텀점','미적분1 개별진도 (이영환T)','수학','이영환','고2',ARRAY['화','목']::text[],'오후','17:00-20:00','주 2회',null,null,'개별진도',ARRAY['5','6','7','8','9','10','11','12']::text[],'개인별 맞춤 교재+진도','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
insert into public.courses (id,city,area,academy_name,course,subject,teacher,grade,days,period,time,sessions,school,school_grade,course_type,months,note,status) values ('eduin67','부산','센텀','교육인학원 센텀점','미적분1 수능대비 (강필T)','수학','강필','고2',ARRAY['일']::text[],'저녁','17:30-21:30','주 1회',null,null,'수능대비',ARRAY['5','6','7','8','9','10','11','12']::text[],'1등급 목표','published')
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
on conflict (id) do update set course=excluded.course, teacher=excluded.teacher, days=excluded.days, period=excluded.period, time=excluded.time, sessions=excluded.sessions, months=excluded.months, note=excluded.note, course_type=excluded.course_type, school=excluded.school, school_grade=excluded.school_grade;
